version: '3.8'

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "80:80"
    depends_on:
      - server
    networks:
      - bp-network

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    environment:
      - NODE_ENV=production
    volumes:
      - bp-data:/app/data
    networks:
      - bp-network
  
  backup-service:
    build:
      context: .
      dockerfile: Dockerfile.backup
    container_name: bp-tracker-backup
    ports: 
      - 3002:3002
    restart: unless-stopped
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_BUCKET=${AWS_BUCKET}
      - AWS_REGION=${AWS_REGION}
      - BACKUP_INTERVAL=${BACKUP_INTERVAL:-0 0 * * *}
      - RETENTION_DAYS=${RETENTION_DAYS:-30}
      - API_URL=http://server:3001
    networks:
      - bp-network
    depends_on:
      - server
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3002/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  bp-network:
    driver: bridge

volumes:
  bp-data:
    driver: local
